#!/bin/sh -eu

# SETTINGS
# --------

. CONF

# IMPORTS
# -------

. lib/commit.sh
. lib/commitlist.sh
. lib/file.sh
. lib/filelist.sh
. lib/fileold.sh
. lib/home.sh
. lib/index.sh
. lib/misc.sh
. lib/diff.sh

# MAIN
# ----

# shellcheck disable=2046
set -- $(split "$PATH_INFO" "/")

case "$#" in
# /
0) create_index ;;
# /repo
1) create_home "$1" ;;
# /repo/c
# /repo/f
2)
	case "$2" in
	c) create_commitlist "$1" ;;
	f) create_filelist "$1" ;;
	esac
	;;
# /repo/c/hash
# /repo/f/file
3)
	case "$2" in
	c) create_commit "$1" "$3" ;;
	f) create_file "$1" "${PATH_INFO##/"$1"/f/}" ;;
	esac
	;;
# /repo/f/a/b
# /repo/c/hash/d
4)
	case "$2" in
	c)
    	case "$4" in
        d) create_commitlist "$1" "$3" ;;
        *) create_commit "$1" "$3" ;;
        esac
        ;;
	f) create_file "$1" "${PATH_INFO##/"$1"/f/}" ;;
	esac
	;;
# /repo/f/a/b/c/...
# /repo/c/hash/f/a/b/c/...
# /repo/c/hash/d/hash
*)
	case "$2" in
	f) create_file "$1" "${PATH_INFO##/"$1"/f/}" ;;
	c)
    	case "$4" in
		f) create_fileold "$1" "$3" "${PATH_INFO##/"$1"/c/"$3"/f/}" ;;
		d) create_diff    "$1" "$3" "$5" ;;
		esac
	;;
	esac
	;;
esac
