.Dd 2022-01-27
.Dt "emacs text interfaces" 7
.Os "ulthar cat"
.
.Sh EMACS TEXT INTERFACES
(note: excluding exwm and weird emacs derivations that can do web stuff)

emacs is another common text interface you'll find, notably with more rich
formatting options than many others. while the common joke is that its more
of an operating system than a text editor, i think its more of a text window
plugged into a lisp machine. can do about anything you want, and its been
around long enough where such a thing probably is already made somewhere.

doesnt have many noteworthy default text interfaceness, in fact it has more
than id prefer of menus and the such by default, but its rare to find someone
who uses near stock configuration.

in terms of programs, theres mail clients, smallnet browsers[1], irc clients,
twitter clients, rss readers, and even a web browser. if you really want to
live inside text interfaces and like the idea of lisp machines (im more of a
forth gal myself), its pretty close to perfect. im even tempted to use it quite
a lot, but my distrust of gnu-sized projects keeps me away. (thats a rant for 
another day, if ever)

the defaulting movement is, not commonly liked, but with some plugins/custom
binds its quite solid. theres a very robust vim-like group of plugins called
evil, and its not difficult to create your own with something like ryo modal[2]
ive made some kakoune inspired movement composed of the default actions before,
and i quite liked it.
.
.Sh REFERENCES
.Bd -unfilled
.Lk https://thelambdalab.xyz/elpher/ [1]
.Lk https://github.com/Kungsgeten/ryo-modal [2]
.Ed
