.Sh text interfaces
.
note: this is a current interest and contents will be updated/subject to change

ive always liked text interfaces, both the aesthetics and the practicality, but
ive noticed that theres nearly only the same VT100 terminal interfaces, and im
a little bored of that. so this and linked pages are a little exploration into
the alternatves, where its still a small simple text-focused interface, but 
built upon something other than vt100 sequences, or adds significant new 
possibilities.
.
.Ss sub pages
.
.Bd -unfilled
.Lk plan9-text.ext
.Lk emacs-text.ext
.Ed
.
.Ss terminal-esque

.Lk https://github.com/withoutboats/notty

sadly a dead project (last commit may 2017), it had lofty goals of implementing
basic vt100 sequences in addition to inline media, dropdown menus, and the
ability to subdivide the character screen.

.Lk https://github.com/kovidgoyal/kitty

one of the most popular terminals emulators, includes a custom terminal graphics
implementation, modern keyboard capabilities, and a variety of others.
written half in python and the dev is uh, opinionated to say the least.
