.Dd $Mdocdate$
.Dt CONTACT 7
.Os "Ulthar Cat"
.
.Sh NOTICE
I am lurker, it is in my nature.
I don't participate in much socially but I am there.
Feel free to contact me regardless, if you want to for some reason.
.
.Sh LINKS

.Bl -tag -compact
.It Lk mailto:felinae@ulthar.cat mail
.It Lk https://nixnet.social/fel fedi
.It Lk irc://irc.oftc.net fel @ oftc
.It Lk irc://irc.tilde.chat fel @ tilde
.It Lk irc://irc.libera.chat fel @ libera
.El
