.Dd $Mdocdate$
.Dt ULTHAR.CAT 7
.Os "Ulthar Cat"
.
.Sh ABOUT
Elaina (felinae) she/her
.Pp
perma lurking adhd computer cat.
currently interested in documentation, personal(ized) computing, and simplicity.
.
.Bd -unfilled
.Lk fetch.ansi
.Lk fetch.txt
.Ed
.
.Lk contact.ext contact me
.
.Sh PAGES
.Bd -unfilled
.Lk git/ git repositories
.Lk doc/ unorganized rants and posts
.Ed
.
.Sh EPHEMERAL
.Lk txt/ pastebin
