.\" information
.Dd $Mdocdate$
.Dt grimoire
.Os ulthar.cat
.\" main page
.Bd -literal
   ████          ██ ██
  ░██░          ░██░░
 ██████  █████  ░██ ██ ███████   ██████    █████ 
░░░██░  ██░░░██ ░██░██░░██░░░██ ░░░░░░██  ██░░░██
  ░██  ░███████ ░██░██ ░██  ░██  ███████ ░███████
  ░██  ░██░░░░  ░██░██ ░██  ░██ ██░░░░██ ░██░░░░ 
  ░██  ░░██████ ███░██ ███  ░██░░████████░░██████
  ░░    ░░░░░░ ░░░ ░░ ░░░   ░░  ░░░░░░░░  ░░░░░░
.Sh ABOUT
.Pp
i am fel, varied interest programmer who hops focus before she can accomplish 
anything useful

interests currently include but are not limited to:
.Bl -bullet
.It
jit compilers
.It 
source control
.It 
operating system design
.El
.Sh INDEX
.Pp
.Lk diary/index.EXT diary
.Pp
.Lk neat.EXT neat software
.Sh REPOS
.Pp
.Lk https://git.ulthar.cat personal
.Pp
.Lk https://sr.ht/~fel sourcehut
.Pp
.Lk https://github.com/fe1inae github
.Sh CONTACT
.Pp
.Mt felinae@ulthar.cat
.Pp
.Lk https://matrix.to/#/@fe1inae:matrix.org matrix

