.\" information
.Dd $Mdocdate$
.Dt neat\ stuff
.Os ulthar.cat
.\" control panel
.Lk /index.EXT home
-
.Lk index.EXT back
.\" main page

.Sh OS/KERNEL/DISTRO
.Pp
.Lk https://www.alpinelinux.org/ alpine
lean small linux distro
.Pp
.Lk https://www.openbsd.org/ openbsd
secure and well desgined unix
.Pp
.Lk http://9front.org/ 9front
plan9 but still developed
.Sh COMPOSITORS/WMS
.Pp
.Lk https://gitlab.freedesktop.org/wlroots/wlroots wlroots
makes writing wayland compositors feasible, has many standardized protocols
.Pp
.Lk https://github.com/riverwm/river/ river
bspwm/dwm-esque for wayland
.Pp
.Lk https://github.com/buffet/kiwmi kiwmi
like a wayland abstraction for lua
.Sh TERMINALS/UTILS
.Pp
.Lk https://codeberg.org/dnkl/foot foot
fantastic terminal with sixels and client/server
.Pp
.Lk https://github.com/tmux/tmux tmux
common but underappreciated and underused.
.Sh SHELLS
.Pp
.Lk https://git.busybox.net/busybox/tree/shell/ash.c busybox ash
small posix shell included in busybox
.Pp
.Lk https://fishshell.com/ fish
non-posix shell focused on interactivity
.Sh TEXT EDITORS/INTERFACES
.Pp
.Lk https://github.com/mawww/kakoune/ kakoune
modal editor with focus on interactivity
.Pp
.Lk https://github.com/martanne/vis/ vis
sam and vim smashed together, with a lua scriptable core
.Sh MAIL
.Pp
.Lk https://aerc-mail.org/ aerc
extensible terminal client, works well with git
.Pp
.Lk https://github.com/emersion/hydroxide hydroxide
open source protonmail bridge
.Sh COMMUNICATION
.Pp
.Lk https://github.com/tulir/gomuks gomuks
tui matrix client
.Sh FILES
.Pp
.Lk https://github.com/fangfufu/httpdirfs httpdirfs
http dir as a fuse filesystem
.Pp
.Lk https://github.com/syncthing/syncthing syncthing
clean versatile file syncing. i use for lots of things
.Sh LIBRARIES
.Pp
.Lk https://github.com/nullgemm/termbox_next termbox_next
termbox but from when it wasnt shit
.Sh LANGUAGES
.Pp
.Lk https://github.com/bakpakin/Fennel fennel
lispy, makes writing lua not mind numbing
.Pp
.Lk https://github.com/janet-lang/janet janet
small core decent stdlib bytecode lisp (clojurey)
.Sh DOCUMENTATION/WRITING
.Pp
.Lk https://git.sr.ht/~sircmpwn/scdoc scdoc
minimal markdown-esque to mdoc with good utf8
.Pp
.Lk https://github.com/kristapsdz/lowdown lowdown
markdown to html, gemini, man
.Pp
.Lk https://pandoc.org/ pandoc
fat convert nearly anything to nearly anything
.Sh MISC
.Pp
.Lk https://github.com/rvaiya/keyd keyd
keyboard remapping daemon through kernel (udev/uinput)
