.\" information
.Dd $Mdocdate$
.Dt misc\ testing
.Os ulthar.cat
.\" control panel
.Lk /index.EXT home
-
.Lk index.EXT back
.\" main page
.Sh OwO
.Pp
messy scratchbox of testing mdoc/roff stuff
.Pp
\(*l
.Pp
.TS
box tab(:);
c| c
l| r.
task         : software
_
compositor   : river 
distro       : alpine 
file manager : lf  
image viewer : imv 
kernel       : linux-edge 
mail client  : aerc 
music player : cmus 
shell        : ash 
terminal     : foot tmux 
text editor  : kakoune 
video player : mpv 
web browser  : firefox 
.TE

.Pp
this is scuff on web:
.Pp
.EQ
sin(x over 2)
.EN
